name: Build and Create Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Используем Windows для сборки

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Настройка Qt
      - name: Set up Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2" # Версия Qt
          host: "windows"
          target: "desktop"
          arch: "win64_mingw"
          tools: "tools_win64"

      # 3. Настройка MinGW
      - name: Set up MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

      # 4. Сборка проекта
      - name: Build project
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="C:/Qt/6.8.2/mingw_64/lib/cmake" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      # 5. Копирование зависимостей с помощью windeployqt
      - name: Deploy dependencies
        run: |
          cd build/Release
          windeployqt.exe exile.exe

      # 6. Создание инсталлера с помощью NSIS
      - name: Create installer
        run: |
          choco install nsis -y
          cd ../../
          makensis.exe scripts/installer.nsi

      # 7. Публикация артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exile-installer
          path: build/ExileInstaller.exe
